debug: true

ports:
  http: 3000
  grpc: 4000
  metrics: 9000

sentry:
  dsn: "https://ec575dab711043f9aac76447e1947827@sentry.k8s.golang-mts-teta.ru/18"

users:
  first_user:
    id: 1
    name: "John Doe"
    password: "$2a$04$MSHk3Xd/ZOFzdiBySEGLE.LTYpUzc9By55qhfmoBYaG4LdOZg6W2i" # Passwd: !@#QWE123qwe

  second_user:
    id: 2
    name: "Michael Jackson"
    password: "$2a$04$MSHk3Xd/ZOFzdiBySEGLE.LTYpUzc9By55qhfmoBYaG4LdOZg6W2i" # Passwd: !@#QWE123qwe

  third_user:
    id: 3
    name: "test123"
    password: "$2a$12$6kx0HmPA.O66v9cCNpr/f.RH.o3aWskap4wCN1q5fX.rx8cw9jjEW" # Passwd: qwerty

token:
  secret: "AFoY0waWhv2AYynuVRBTC0b0msyQv2ESfFLdAzRBGAh1izFTZ3Zerthz07FH2W0m"

  accessToken:
    ttl: 60

  refreshToken:
    ttl: 3600