MODE: "debug"

HTTP: "8626"
GRPC: "4000"
METRICS: "9000"

SENTRY_DSN: "https://ec575dab711043f9aac76447e1947827@sentry.k8s.golang-mts-teta.ru/18"

db:
  name: "postgres"
  sslMode: "disable"
  host: "91.185.93.23"
  port: "5432"
  postgres_user: "team32"
  postgres_password: "mNgdyMTbhVGd"

token:
  secret: "AFoY0waWhv2AYynuVRBTC0b0msyQv2ESfFLdAzRBGAh1izFTZ3Zerthz07FH2W0m"

  accessToken:
    ttl: 60

  refreshToken:
    ttl: 3600